### ISSUE TITLE
running we-get without any params throws an uncaught exception

### ISSUE THREAD

**Issue by TylerNakamura** [0xl3vi/we-get#6]
* Platform:
macOS
### Description
just running ```we-get``` will throw an uncaught exception

Describe what is the issue and how to reproduce.

optional: Add terminal screenshot

```13:46 ~/Desktop:we-get
Traceback (most recent call last):
  File "/usr/local/bin/we-get", line 11, in <module>
    load_entry_point('we-get==0.1', 'console_scripts', 'we-get')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/we_get/__init__.py", line 7, in <module>
    from we_get.core.we_get import WG
  File "/usr/local/lib/python2.7/site-packages/we_get/core/we_get.py", line 154
    [print(self.items[item]['link']) for item in self.items]
         ^
SyntaxError: invalid syntax```

**Comment by TylerNakamura** [comment]
I'm dumb. Didn't have Python3 installed on this machine
